#!/usr/bin/env bash
# print domains and subdomains

print_domain_subdomain () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    print_domain_subdomain "$2.$1" "$2"
else
    print_domain_subdomain "www.$1" "www"
    print_domain_subdomain "lb-01.$1" "lb-01"
    print_domain_subdomain "web-01.$1" "web-01"
    print_domain_subdomain "web-02.$1" "web-02"
fi

# or

# DNS_info () {
#     ANSWER=$(dig $2 | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $0}')
#     echo "The subdomain $1 is a $(echo $ANSWER | awk '{print $4}') record and points to $(echo $ANSWER | awk '{print $5}')"
# }

# if [[ $# == 1 ]]; then
#     subdomains=('www' 'lb-01' 'web-01' 'web-02')
#     for i in "${subdomains[@]}"; do
# 	CONCAT="$i.$1"
# 	DNS_info $i $CONCAT
#     done
# else
#     CONCAT="$2.$1"
#     DNS_info $2 $CONCAT
# fi
