#!/usr/bin/env bash
# A Bash script to transfer file from a client to a server.
# Using the scp linux command, we're taking  the following arguments
# PATH_TO_FILE to be copied to server, USER on server IP of server
# LOCATION to copy to on server and PATH_TO_IDENTITY_FILE for user auth

if [ $# -lt 4 ]
	then
		echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'

	else
		scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi


# now we need to connect to our remote server 
# ssh ubuntu@100.26.178.1 -i /home/ubuntu 'ls ~/'

# the above would display what is on your server

# let create the file 
#touch some_page.html

#let tranfer file to server
#0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
#./0-transfer_file some_page.html 100.26.178.1 ubuntu  ~/.ssh/school

# confirm it tranfer:
# ssh ubuntu@100.26.178.1 -i /home/ubuntu 'ls ~/'