#!/usr/bin/env bash

# A script that installs nginx server on an ubuntu linux distro.
# The installed server listens to port 80 (HTTP) for connection
# And serves a default page index.html on the HTTP  GET request.

sudo apt-get update -y

# what does -y mean in this context click Read me to see -> [Read me](https://intranet.alxswe.com/rltoken/KJiFZ4yJyTGp_cv3DYQLaQ)

sudo apt-get install nginx -y

echo 'Hello World!' > /var/www/html/index.html

service nginx restart # or  u can also use systemctl to restart nginx


# In this example 34.198.248.145 is the IP of my web-01 server. If you want to query the Nginx that is locally installed on your server, you can use curl 127.0.0.1.

#If things are not going as expected, make sure to check out Nginx logs, they can be found in /var/log/.