#!/usr/bin/env bash
# A Bash script to transfer file from a client to a server.
# Using the scp linux command, we're taking  the following arguments
# PATH_TO_FILE to be copied to server, USER on server IP of server
# LOCATION to copy to on server and PATH_TO_IDENTITY_FILE for user auth

if [ $# -lt 4 ]
	then
		echo 'Usage: some_page.html /alx-system_engineering-devops 100.26.178.1 ubuntu ~/.ssh/school'

	else
		scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi
