#!/usr/bin/env bash
# A bash script that installs nginx on an ubuntu machine.
# This scripts also configures the default webpage served to be "Hello World!"
# When request url matches /redirect_me, it redirects to my youtube channel.

# echo -e "Updating and installing ${brown}Nginx.\n"
# sudo apt-get update -y -qq && \
# 	 sudo apt-get install nginx -y

# echo -e "\nSetting up some minor stuff.\n"

# # starting nginx service
# sudo service nginx start

# # allowing nginx on firewall
# sudo ufw allow 'Nginx HTTP'

# # Give the user ownership to website files for easy editing
# sudo chown -R "$USER":"$USER" /var/www/html
# sudo chmod -R 755 /var/www

# # Backup default index
# cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# # Creating new index
# echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# # Setting up /redirect_me to a mine site
# sudo sed -i '24i\	rewrite ^/redirect_me https://www.effiongsamuel.tech;' /etc/nginx/sites-available/default

# # Restarting nginx
# sudo service nginx restart

# echo -e "\nCompleted.\n"

# or
# sudo apt-get update
# sudo apt-get install -y nginx

# echo "Hello World!" | sudo tee /var/www/html/index.html
# string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.akotech.com permanent;"
# sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# sudo service nginx restart


# sudo apt-get -y update
# sudo apt-get -y install nginx

# echo -e "\nSetting up some minor stuff and peace  .\n"

# # starting nginx service on server
# sudo service nginx start

# # allowing nginx on firewall
# sudo ufw allow 'Nginx HTTP'

# # Give the user ownership to website files for easy editing
# sudo chown -R "$USER":"$USER" /var/www/html
# sudo chmod -R 755 /var/www

# # Backup default index
# cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# touch /var/www/html/index.html
# echo "Hello World!" > /var/www/html/index.html

# printf %s "server {
#     listen		80 default_server;
#     listen		[::]:80 default_server;

#     root		/var/www/html;
#     index		index.html index.htm index.nginx-debian.html;

#     location /redirect_me {
#         return 301 https://www.effiongsamuel.tech;
#     }
# }
# " > /etc/nginx/sites-available/default

# service nginx restart



# A bash script that installs nginx on an ubuntu machine.
# This scripts also configures the default webpage served to be "Hello World!"
# When request url matches /redirect_me, it redirects to my youtube channel.

sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

NEW_RULE="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://www.effiongsamuel.tech;\n\t}\n"

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bakup

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

sudo service nginx restart
