#!/usr/bin/env bash
# A bash script that installs nginx on an Ubuntu machine.
# Configures a custom 404 page with the text "Ceci n'est pas une page".
# Redirects /redirect_me to a specified URL.

# Update package list and install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Create a default index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Create a custom 404.html page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Backup the default Nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

# Add redirection rule
REDIRECT_RULE='location /redirect_me {
    return 301 https://www.youtube.com/@samueleffiong7502;
}
'
sudo sed -i "/server_name _;/a $REDIRECT_RULE" /etc/nginx/sites-available/default

# Add custom 404 page configuration
ERROR_PAGE_RULE='
error_page 404 /404.html;
location = /404.html {
    internal;
}
'
sudo sed -i "/server_name _;/a $ERROR_PAGE_RULE" /etc/nginx/sites-available/default

# Test Nginx configuration for syntax errors
sudo nginx -t

# Reload Nginx to apply the changes
sudo systemctl reload nginx
