#!/usr/bin/env bash
# A bash script that installs nginx on an ubuntu machine.
# This scripts also configures the default webpage served to be "Hello World!"
# When request url matches /redirect_me, it redirects to my youtube channel.
# When a page/file not found in the document root is requested, the 404.html
# page is served to the client as stated with the error_page directive.

# echo -e "Updating and installing Nginx.\n"
# sudo apt-get update -y -qq && \
# 	 sudo apt-get install nginx -y

# echo -e "\nSetting up some minor stuff.\n"

# # starting nginx service
# sudo service nginx start

# # allowing nginx on firewall
# sudo ufw allow 'Nginx HTTP'

# # Give the user ownership to website files for easy editing
# sudo chown -R "$USER":"$USER" /var/www/html
# sudo chmod -R 755 /var/www

# # Backup default index
# cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# # Creating new index
# echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# # Setting up /redirect_me to a youtube video
# sudo sed -i '24i\	rewrite ^/redirect_me https://www.effiongsamuel.tech;' /etc/nginx/sites-available/default

# # Set up a 404 page
# echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
# sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# # Restarting nginx
# sudo service nginx restart

# echo -e "\nCompleted.\n"

# or 

# sudo apt-get update
# sudo apt-get install -y nginx

# # code to redirect a specific endpoint (eg: redirect /redirect_me to https://akotech.com)
# echo "Hello World!" | sudo tee /var/www/html/index.html
# string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.akotech.com permanent;"
# sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# # code to create error page and add a redirect for error 404
# echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
# string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
# sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# # restart the server
# sudo service nginx restart

apt-get update
apt-get install -y nginx

touch /var/www/html/index.html /var/www/html/404.html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   root   /var/www/html/;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=TfgBHC5gvTI;
    }

    error_page 404 /404.html;
    location /404 {
        root /var/www/html/;
        internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
