#!/usr/bin/env bash
# Configures a new Ubuntu machine

# Update package index and install Nginx
apt-get -y update
apt-get -y install nginx

# Add custom response header to know the server name for debugging
HOST_NAME=$(hostname)
HEADER="add_header X-Served-By $HOST_NAME;"
CONF_FILE="/etc/nginx/sites-available/default"

# Check if the custom header already exists
if ! grep -q "X-Served-By" $CONF_FILE; then
    # Add the custom header to the server block
    sudo sed -i "/server {/a \    $HEADER" $CONF_FILE
fi

# Create a default index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Add a redirection to another page
REDIRECT_STRING="location /redirect_me { return 301 https://www.youtube.com/@samueleffiong7502; }"
if ! grep -q "redirect_me" $CONF_FILE; then
    # Add the redirection to the server block
    sudo sed -i "/server {/a \    $REDIRECT_STRING" $CONF_FILE
fi

# Add a custom 404 error page
ERROR_PAGE="error_page 404 /custom_404.html;"
if ! grep -q "error_page 404" $CONF_FILE; then
    echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
    # Add the error page directive to the server block
    sudo sed -i "/server {/a \    $ERROR_PAGE" $CONF_FILE
fi

# Restart Nginx to apply changes
sudo systemctl restart nginx
