#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
echo -e "Updating ubuntu doing some minor checks...\n"
sudo apt-get -y update
echo -e  "HAproxy INSTALLING BEGINS"
sudo apt-get -y install haproxy=1.6.\*

echo -e "haproxy INSTALLING ends"
# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend www.effiongsamuel.tech
        bind 54.237.56.1:80
        default_backend effiongsamuel_tech_backend

backend effiongsamuel_tech_backend
        balance roundrobin
        server 139694-web-02 34.202.157.245:80
        server 139694-web-01 100.26.178.1:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart

echo -e "service setup sucessful"

echo -e "view version of haproxy install"

# VIEWING HAPROXY
haproxy -v

#
sudo service haproxy status

#https://www.linuxtechi.com/install-configure-haproxy-on-ubuntu/