#!/bin/bash
chown -h vincent:staff _hello

# Write a script that changes the owner and the group owner of _hello to vincent and staff respectively.

# The file _hello is in the working directory
# The file _hello is a symbolic link