#!/bin/bash
chown --from=guillaume betty hello


#Write a script that changes the owner of the file hello to betty only if it is owned by the user guillaume.

#The file hello will be in the working directory