#!/bin/bash
chmod 753 hello

# Write a script that sets the mode of the file hello to this:

```bash -rwxr-x-wx 1 julien julien 23 Sep 20 14:25 hello``
# The file hello will be in the working directory
# You are not allowed to use commas for this script