#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times.

if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi


# The Internet Control Message Protocol (ICMP) is a protocol in the Internet protocol suite. It is used by network devices, to check if other network devices are available on the network. The command ping uses ICMP to make sure that a network device remains online or to troubleshoot issues on the network.

# Write a Bash script that pings an IP address passed as an argument.

# Requirements:

# Accepts a string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# Ping the IP 5 times
# ./5-is_the_host_on_the_network 8.8.8.8