#!/usr/bin/env bash
# script that restores the default server port

# not this below is woeking
#======================================

# sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# sudo service nginx start

#========================================

#./0-nginx_likes_port_80 > /dev/null 2&>1

#or 

new_one = "80 default_server"
old_one = "8080 default_server"

sed -i "s/$old_one/$new_one/"  /etc/nginx/sites-enabled/default

service ngninx start