#!/usr/bin/env bash

# Installs firewall; block all incoming except 22, 443, 80

echo -e "SAMUEL EFFIONG YOUR FIREWALL FOR ALX SCHOOL AND effiongsamuel.tech was is about to being please make sure to have internet connect.\n"

echo -e "Updating\n ===============================================================>"

sudo apt-get update
echo -e "Updating completed and starting fire wall installation\n ===============================================================>"

echo -e "Installing UFW started\n ========================================================================>"

sudo apt-get install -y ufw
sudo sed -i "s/IPV6=.*/IPV6=yes/" /etc/default/ufw

echo -e "installation completed and configuring UFW...\n =================================================>"

# Allow Outgoing and Deny Incoming
sudo ufw default deny incoming
sudo ufw default allow outgoing
echo -e "installation completed and configuring UFW... completed\n =================================================>"
# Allow ports
echo -e "Enable Fire Wall port 22/tcp.\n ========================================>"
sudo ufw  allow 22/tcp
echo -e "Enable Fire Wall port 22 completed.\n ========================================>"

echo -e "Enable Fire Wall port 80/tcp.\n ========================================>"
sudo ufw allow 80/tcp
echo -e "Enable Fire Wall port 80/tcp completed.\n ========================================>"

echo -e "Enable Fire Wall port 443/tcp.\n ========================================>"
sudo ufw allow 443/tcp
echo -e "Enable Fire Wall port 443/tcp completed.\n ========================================>"

# Enable Fire Wall
echo -e "Enable Fire Wall.\n ========================================>"
sudo ufw enable

echo -e "Process Completed.\n ========================================>"

echo -e "SAMUEL EFFIONG YOUR FIREWALL FOR ALX SCHOOL AND effiongsamuel.tech was successful.\n =========================================>"

echo -e "CHECK FIRE WALL STATUS \n ========================> "
