#!/usr/bin/env bash

# Installs firewall; block all incoming except 22, 443, 80

sudo apt-get update

sudo apt-get install -y ufw
sudo sed -i "s/IPV6=.*/IPV6=yes/" /etc/default/ufw

# Allow Outgoing and Deny Incoming
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow ports
sudo ufw  allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# start	
sudo ufw enable
