#!/usr/bin/env bash
# Fixes server bug
#=================================
#first check the status of service
#service ngix status

#granting permission for nginx to run as user
chmod 644 /etc/nginx/nginx.conf
# change directory to ngix using regular expressio
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default

# kill any apache server running
pkill apache2
# restart
su nginx -s /bin/bash -c 'service nginx restart'

#after debugging do
#ps auxff | grep ngin[x]

#nc -z 8080 ; echo $?
#====================================
#sencod approch Below
#===========================

# this kill apache2 server
#pkill apache2

#change any available directory to file congration
#sed -i 's/80 default_server/8080 default_server/'  /etc/nginx/sites-available/d\efault

#granting permission to ngix file congufiration if exit || this may not be necerssary on some server 
#chown nginx:nginx /etc/nginx/nginx.conf

# starting service #service nginx reload
#service nginx restart

# when ever u want stop nginx server 
# service ngix stop